app = "twq"
primary_region = "cdg"

[[services]]
  internal_port = 25
  protocol = "tcp"

  [[services.ports]]
    port = 25

[processes]
  app = ""

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
