app = "twq"
primary_region = "cdg"

[[services]]
  internal_port = 25 # نغير المنفذ الداخلي ليطابق Haraka
  protocol = "tcp"

  [[services.ports]]
    handlers = []
    port = 25 # استقبال بريد SMTP العادي
