app = "twq"
primary_region = "cdg"

[[services]]
  internal_port = 25
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 25

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
